### ISSUE TITLE
Does the Fluent NHibernate provider work?

### ISSUE THREAD

**Issue by stevetruckstuff** [Alachisoft/NCache#2]
In the NHibernate integration source, I noticed there is a file called `NCacheProvider.cs` that implements `ICacheProvider`.  However the class is internal, not public, and all of the NCache examples and documentation use XML configurations.  If modified to be public, will the `NCacheProvider` class serve as a cache provider for Fluent configurations?

**Comment by NCacheDev** [comment]
Currently, we do not support NHibernate fluent configuration. We are planning to provide support in upcoming releases.

**Comment by kfinke70** [comment]
Has there been any update on this?  If not, are there any workarounds?

**Comment by bkhairy** [comment]
Is it still not supported in fluent configurations?
