### ISSUE TITLE
Cannot install Alachisoft.NCache.Community.EFCore in an ASP.NET Core 2.2 application

### ISSUE THREAD

**Issue by Alexei000** [Alachisoft/NCache#44]
I am trying to install Alachisoft.NCache.Community.EFCore in an ASP.NET Core 2.2 application and I have a dependency issue:

`Install-Package Alachisoft.NCache.Community.EFCore –Version 4.9.0`

> Restoring packages for ... 
> Installing System.Management.Automation.dll 10.0.10586.0.
> Installing Mono.Cecil 0.9.6.4.
> Installing Alachisoft.NCache.Community.SDK 4.9.0.
> Installing Alachisoft.NCache.Community.EFCore 4.9.0.
> NU1608: Detected package version outside of dependency constraint: Alachisoft.NCache.Community.SDK 4.9.0 requires System.Data.SqlClient (= 4.4.0) but version System.Data.SqlClient 4.6.0 was resolved.
> NU1701: Package 'Mono.Cecil 0.9.6.4' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.
> NU1701: Package 'System.Management.Automation.dll 10.0.10586' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.

.csproj data that might be relevant:

```
<TargetFramework>netcoreapp2.2</TargetFramework>
<PackageReference Include="Microsoft.AspNetCore.App" />
<PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
<PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.1.0" />
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.2.4" />
<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.4" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.2.4">
```
How can I fix this issue?

Thank you.

**Comment by Alexei000** [comment]
I think I figured it out. NuGet manager shows latest stable as 4.9.0.1, but I was able to successfully install version 5.0,1:

`Install-Package Alachisoft.NCache.OpenSource.EFCore -Version 5.0.1`

**Comment by Brad-NCache** [comment]
Hi Alexei,

From your last post, I gather that your issue is resolved. If not, please do let me know and I will try to assist you.

**Comment by Alexei000** [comment]
Hello Brad,

Yes, I have managed to get started with the OpenSource version instead of Community as indicated and also managed to get it working in the simple scenario I needed. 

Thanks.
