### ISSUE TITLE
Backing source not available. Verify backing source settings.

### ISSUE THREAD

**Issue by PagePinner** [Alachisoft/NCache#47]
Hi,
I have configured the back source node in config.ncconfig as below:
&#x3C;configuration&#x3E;
&#x3C;cache-config cache-name=&#x22;TestCacheName&#x22;&#x3E;
...
&#x3C;backing-source&#x3E;
        &#x3C;read-thru enable-read-thru=&#x22;True&#x22;&#x3E;
          &#x3C;provider provider-name=&#x22;sqlreadthruprovider&#x22; assembly-name=&#x22;BackingSource.Providers.Sql, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null&#x22; class-name=&#x22;Alachisoft.NCache.Samples.Providers.SqlReadThruProvider&#x22; full-name=&#x22;BackingSource.Providers.Sql.dll&#x22; default-provider=&#x22;False&#x22;&#x3E;
            &#x3C;parameters name=&#x22;connstring&#x22; value=&#x22;Data Source=localhost;Database=northwind;User Id=admin;password=xxxxxxxx;&#x22;/&#x3E;
          &#x3C;/provider&#x3E;
        &#x3C;/read-thru&#x3E;      
 &#x3C;/backing-source&#x3E;
&#x3C;/cache-config&#x3E;
&#x3C;/configuration&#x3E;

And deploy the read through provider under NCache/deploy/TestCacheName folder. 
But the read through is not working: error is **Backing source not available. Verify backing source settings.**

Does anyone know how to make Read through work with open source edition?

**Comment by Kal-Alachisoft** [comment]
Hi @PagePinner , can you share some more details.

Please share snippets of the Cache logs where this error is logged if they're being created. Where are you getting the error "Backing source not available. Verify backing source settings.". You can even attach the complete log file as well.

**Comment by PagePinner** [comment]
It is working now. I put backing-source node under the wrong node.  Should be under <cache-settings> Thanks.
