### ISSUE TITLE
NCache Open Source 5.0 SP1- Unable to start cache after installation. Throw 'Specified cacheId is not registered' exception.

### ISSUE THREAD

**Issue by DamienLaw** [Alachisoft/NCache#51]
![image](https://user-images.githubusercontent.com/14930009/65413119-3f602d00-de23-11e9-9b1b-604268705c45.png)

I've uninstalled the previous Open Source version (5.0) and installed this version (5.0 SP1). The cache won't even start. I already copied over the *client.ncconf* and *config.ncconf* which I backed up from the previous version.

**Comment by Kal-Alachisoft** [comment]
Hi @DamienLaw , from the error it seems like the name you're specifying in the start-cache command is not present within the configs the NCache service is looking in. 

You mentioned that you've copied the older configs into the new installed directory, please confirm if you restarted the NCache Service after that? The NCache service may be using an older copy of the config.ncconf which it loaded at service started up.

Furthermore, the Cache names are not case sensitive but please make sure the name you're specifying within the command is also present within the configs,

I hope this helps.

**Comment by DamienLaw** [comment]
As it turns out, the latest version 5.0 SP1, requires that the `<cache-config>` node in *config.ncconf* to have an additional attribute - **config-id**.

```<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<configuration>
	<cache-config cache-name="myCache" config-id="7d4709e2-eb28-4599-b778-4b2138a0c468">
....

There's no documentation or "What's new in 5.0 SP1" to be found that mention this breaking change.

**Comment by korau** [comment]
The above mentioned config-id solution does not appear to resolve this error in OSS 5.0 SP3.

![50sp3oss](https://user-images.githubusercontent.com/54726524/92075981-ef446580-edfc-11ea-98b3-a8551afb7093.jpg)

The cache itself is listed when running a Get-Caches cmdlet on the server, so it is being detected to some extent.
