### ISSUE TITLE
NCache cann´t be installed on AWS virtual Machine. Please use "NCache OpenSource" AWS Image.

### ISSUE THREAD

**Issue by andrevoltolini** [Alachisoft/NCache#60]
Hi, when trying to install SP3 on a virtual machine on AWS and I got the following message:

**NCache cann´t be installed on AWS virtual Machine. Please use "NCache OpenSource" AWS Image.**

I then used the SP2 version successfully. I looked for this AWS Image and found nothing. Does anyone have any idea what's going on? Will I no longer be able to install on a VM on AWS? Thank you very much for any help.

**Comment by Dan-Ahmed** [comment]
Hi @andrevoltolini ,

I have reviewed this and after discussion with our engineering, I can confirm that there was a limitation introduced in AWS and Azure environments where we enforced that NCache installation is only possible through Marketplace images. We immediately saw some issues with this policy and it is being reverted in NCache 5.0 SP4 version.

For Current NCache 5.0 SP3 version available on our download page. You can use below command to install this in AWS and Azure environments.

Please use the following command `NCache5.0_Enterprise_DotNet_x64.msi SKIPCLOUDCHECK="1"` to install NCache on cloud machines. The **“SKIPCLOUDCHECK”** allows user to install NCache on cloud machines.

I hope this resolves your issue.

**Comment by andrevoltolini** [comment]
Hi @Dan-Ahmed, thanks for the reply. I will plan to upgrade SP3 to SP4 next weekend. As soon as I have the results, I'll let you know. Thanks again.

**Comment by andrevoltolini** [comment]
Hi @Dan-Ahmed ,i hope you are well. The parameter in the installation worked correctly, thank you very much.
