### ISSUE TITLE
Disable all server logs not working

### ISSUE THREAD

**Issue by andrevoltolini** [Alachisoft/NCache#65]
I hope everyone is doing well. I'm trying to configure the NCache service so that it doesn't log. I followed the following instructions [Config logging](https://www.alachisoft.com/resources/docs/ncache-pro/admin-guide/logging-config.html). But I wasn't successful and the amount of logs generated is getting in the way. On all clients config the logs are disabled.

Folder:
C:\Program Files\NCache\log-files\cacheName_5-8-2021-21-43-30_114.14.1.16.txt

Sample of the log file:
LEVEL    	MESSAGE
INFO     	CacheInfo                     
INFO     	ConnectionTable.Start         
INFO     	TCP.start                     
INFO     	ClientGmsImpl.Join            
INFO     	GMS.InstallView               
INFO     	GMS.InstallView               
INFO     	GMS.InstallView               
INFO     	GMS.InstallView               
INFO     	ClusterService.ViewAccepted   
INFO     	ClusterService.OnMemberJoined 
INFO     	Cache.Initialize              

Server version: 5.0.4.0 Open source

**Comment by Dan-Ahmed** [comment]
Hi @andrevoltolini, 

You can turn off the Cache logs in the "config.ncconf" file for the concerned Cache. This is located at "C:\Program Files\NCache\config". There is a "<logging />" tag for each Cache and you can enable/disable logging using this tag. It should look somewhat similar to this.

`<logging enable-logs="False" trace-errors="False" trace-notices="False" trace-warnings="False" trace-debug="False" log-path=""/>`

**Comment by andrevoltolini** [comment]
Hi, @Dan-Ahmed,

Works, thanks.
